postgres:
    build: ./postgres
    expose:
        - 5432
    tty: true
    stdin_open: true

kong:
    build: ./kong
    links:
        - postgres
    ports:
        - "8000:8000"
        - "8001:8001"
        - "22"
    expose:
        - "8000"
        - "8001"
        - "22"
    tty: true
    stdin_open: true
