postgres:
    build: ./postgres
    expose:
        - 5432

kong:
    build: ./kong
    links:
        - postgres
    ports:
        - "8000:8000"
        - "8001:8001"
        - "8022:22"
    expose:
        - "8000"
        - "8001"
        - "22"
