dashboard:
    build: ./kong-dashboard
    links:
        - kong
    expose:
        - 8080
    ports:
        - "9001:8080"

httpbin:
    build: ./httpbin
    expose:
        - 80
    ports:
        - "9000:80"

postgres:
    build: ./postgres
    expose:
        - 5432

postgres_tests:
    build: ./postgres
    expose:
        - 5432
    environment:
        - POSTGRES_DB=kong_tests

kong:
    build: ./kong
    links:
        - postgres
        - httpbin
        - redis
    ports:
        - "8000:8000"
        - "8001:8001"
        - "8022:22"
    expose:
        - "8000"
        - "8001"
        - "22"

redis:
  build: ./redis
  expose:
    - 6379
  ports:
    - "6379:6379"
  volumes:
    - /srv/docker/redis:/var/lib/redis
  restart: always
